---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exome-results-browsers
  labels:
    service: exome-results-browsers
spec:
  replicas: 1
  selector:
    matchLabels:
      name: exome-results-browsers
  template:
    metadata:
      labels:
        name: exome-results-browsers
    spec:
      containers:
        - name: app
          image: us-docker.pkg.dev/exac-gnomad/gnomad/exome-results-browsers
          env:
            - name: RESULTS_DATA_DIRECTORY
              value: /mnt/disks/erb-data/results
            - name: TRUST_PROXY
              value: '2'
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /mnt/disks/erb-data
      volumes:
        - name: data
          gcePersistentDisk:
            fsType: ext4
            pdName: exome-results-browsers-data-230123-1052-east1c
            readOnly: true
